const destinations = [
  // ===== Culture =====
  {
    name: "Sigiriya Rock Fortress",
    category: "culture",
    duration: 1,
    cost: 4000,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sigiriya_%28141688197%29.jpeg/1200px-Sigiriya_%28141688197%29.jpeg",
    description: "Ancient rock fortress with royal gardens and breathtaking views.",
    lat: 7.9575,
    lon: 80.7600,
  },
  {
    name: "Kandy Temple of the Tooth",
    category: "culture",
    duration: 1,
    cost: 2500,
    image: "https://whc.unesco.org/uploads/thumbs/site_0450_0020-1200-630-20151105154018.jpg",
    description: "Sacred Buddhist temple that houses the tooth relic of Lord Buddha.",
    lat: 7.2906,
    lon: 80.6337,
  },
  {
    name: "Anuradhapura",
    category: "culture",
    duration: 2,
    cost: 3500,
    image: "https://d1bv4heaa2n05k.cloudfront.net/user-images/1533888386047/shutterstock-307224302_destinationMain_1533888398803.jpeg",
    description: "Ancient capital with centuries-old stupas and monasteries.",
    lat: 8.3114,
    lon: 80.4037,
  },
  {
    name: "Polonnaruwa Ancient City",
    category: "culture",
    duration: 2,
    cost: 3200,
    image: "https://media.istockphoto.com/id/824016044/photo/vintage-colour-effect-of-polonnaruwa-ancient-vatadage.jpg?s=612x612&w=0&k=20&c=8xPi05YUMvle7Y2Xz3y0Gspk-ZhYnyf9N4Z8Rytwp10=",
    description: "UNESCO World Heritage site with ancient palaces and temples.",
    lat: 7.9397,
    lon: 81.0000,
  },
  {
    name: "Dambulla Cave Temple",
    category: "culture",
    duration: 1,
    cost: 2200,
    image: "https://www.historyhit.com/app/uploads/bis-images/5163366/shutterstock_Dambulla-Cave-Temple-1-788x537.jpg?x81146",
    description: "Famous cave temple with ancient Buddha statues and murals.",
    lat: 7.8564,
    lon: 80.6490,
  },
  {
    name: "Galle Fort",
    category: "culture",
    duration: 1,
    cost: 2000,
    image: "https://do6raq9h04ex.cloudfront.net/sites/8/2021/07/galle-fort-1050x700-1.jpg",
    description: "UNESCO heritage fort with colonial charm and ocean views.",
    lat: 6.0320,
    lon: 80.2167,
  },
  {
    name: "Jaffna Fort",
    category: "culture",
    duration: 1,
    cost: 2000,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Jaffna_Fort_%281%29.jpg/500px-Jaffna_Fort_%281%29.jpg",
    description: "Historical fort built by the Portuguese, later expanded by Dutch.",
    lat: 9.6615,
    lon: 80.0255,
  },
  {
    name: "Matale Spice Garden",
    category: "culture",
    duration: 1,
    cost: 1800,
    image: "https://dea.gov.lk/wp-content/uploads/2022/03/img11.jpg",
    description: "Explore aromatic spices and traditional herbal remedies.",
    lat: 7.4667,
    lon: 80.6167,
  },
  {
    name: "National Museum Colombo",
    category: "culture",
    duration: 1,
    cost: 1200,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/SL_Colombo_asv2020-01_img10_National_Museum.jpg/1200px-SL_Colombo_asv2020-01_img10_National_Museum.jpg",
    description: "Largest museum in Sri Lanka showcasing artifacts and history.",
    lat: 6.9271,
    lon: 79.8612,
  },
  {
    name: "Independence Memorial Hall",
    category: "culture",
    duration: 1,
    cost: 1000,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Independence_Commemoration_Hall.jpg/1280px-Independence_Commemoration_Hall.jpg",
    description: "Historical landmark built to commemorate Sri Lanka's independence.",
    lat: 6.9271,
    lon: 79.8625,
  },

  // ===== Beach =====
  {
    name: "Mirissa Beach",
    category: "beach",
    duration: 2,
    cost: 5000,
    image: "https://digitaltravelcouple.com/wp-content/uploads/2020/01/mirissa-beach-sri-lanka-1.jpg",
    description: "Perfect for whale watching, surfing, and golden sunsets.",
    lat: 5.9489,
    lon: 80.4540,
  },
  {
    name: "Arugam Bay",
    category: "beach",
    duration: 3,
    cost: 6500,
    image: "https://tuktukrental.com/arugam-bay-travel-guide-sri-lanka/",
    description: "World-famous surf spot with a chill tropical vibe.",
    lat: 6.8413,
    lon: 81.6980,
  },
  {
    name: "Bentota Beach",
    category: "beach",
    duration: 2,
    cost: 4000,
    image: "https://travel.com/wp-content/uploads/2025/09/Aerial-view-of-Bentota-Beach-where-the-river-meets-the-Indian-Ocean-on-a-sunny-day-in-Sri-Lanka.webp",
    description: "Golden sands, calm seas, and luxury beach resorts.",
    lat: 6.4250,
    lon: 80.0070,
  },
  {
    name: "Unawatuna Beach",
    category: "beach",
    duration: 1,
    cost: 3000,
    image: "https://www.wondersofceylon.com/content/images/2024/01/WoC-Unawatuna-Beach-Featured.webp",
    description: "Popular beach for swimming and snorkeling.",
    lat: 6.0322,
    lon: 80.2470,
  },
  {
    name: "Nilaveli Beach",
    category: "beach",
    duration: 1,
    cost: 2800,
    image: "https://digitaltravelcouple.com/wp-content/uploads/2019/12/nilaveli-beach-sunrise.jpg",
    description: "Beautiful white sand beach near Pigeon Island National Park.",
    lat: 8.9200,
    lon: 81.2320,
  },
  {
    name: "Trincomalee Beach",
    category: "beach",
    duration: 1,
    cost: 2900,
    image: "https://www.thecoastalcampaign.com/wp-content/uploads/2019/10/DJI_0207-2.jpg",
    description: "Coastal city with calm beaches and diving spots.",
    lat: 8.5870,
    lon: 81.2150,
  },
  {
    name: "Kalpitiya Beach",
    category: "beach",
    duration: 2,
    cost: 3500,
    image: "https://d3sftlgbtusmnv.cloudfront.net/blog/wp-content/uploads/2024/08/Kalpitiya-Beach-Cover-Photo-840x425.jpg",
    description: "Ideal for kitesurfing and dolphin watching.",
    lat: 8.0833,
    lon: 79.7667,
  },
  {
    name: "Hikkaduwa Beach",
    category: "beach",
    duration: 1,
    cost: 2700,
    image: "https://ceylonclassictours.com/wp-content/uploads/2023/09/hikkaduwa-beach.jpg",
    description: "Coral reefs, surfing, and nightlife spot.",
    lat: 6.1425,
    lon: 80.1044,
  },
  {
    name: "Uppuveli Beach",
    category: "beach",
    duration: 1,
    cost: 2800,
    image: "https://mediaim.expedia.com/destination/2/9b6649642a3d0df92f0616497e0b5e00.jpg",
    description: "Tranquil beach with soft sands and clear water.",
    lat: 8.6000,
    lon: 81.2500,
  },
  {
    name: "Tangalle Beach",
    category: "beach",
    duration: 2,
    cost: 4000,
    image: "https://nerdnomads.com/wp-content/uploads/2014/03/DSC3444.jpg",
    description: "Secluded beach with palm-lined coastline.",
    lat: 6.0100,
    lon: 80.7900,
  },

  // ===== Nature =====
  {
    name: "Ella",
    category: "nature",
    duration: 1,
    cost: 3000,
    image: "https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1228",
    description: "Charming hill town surrounded by misty mountains and tea estates.",
    lat: 6.8390,
    lon: 81.0440,
  },
  {
    name: "Nuwara Eliya",
    category: "nature",
    duration: 2,
    cost: 4500,
    image: "https://media.istockphoto.com/id/510481818/photo/waterfall-valley-near-nuwara-eliya-sri-lanka.jpg?s=612x612&w=0&k=20&c=d4Hqe_BQ_-1y1QLCAPlj5vLJ8zgpgnBX1JiJMDeKiEI=",
    description: "Known as 'Little England', famous for tea gardens and cool weather.",
    lat: 6.9700,
    lon: 80.7890,
  },
  {
    name: "Horton Plains",
    category: "nature",
    duration: 1,
    cost: 3500,
    image: "https://www.srilankanexpeditions.co.uk/images/sri-lanka-guide/horton-plains-national-park/01.jpg",
    description: "Scenic plateau with World’s End cliff and rich biodiversity.",
    lat: 6.8000,
    lon: 80.7700,
  },
  {
    name: "Adam's Peak",
    category: "nature",
    duration: 2,
    cost: 3500,
    image: "https://www.ceylonexpeditions.com/medias/destination_places/big/110/sri-pada-adam-s-peak-sri-lanka.jpg",
    description: "Famous pilgrimage mountain with sunrise views.",
    lat: 6.8110,
    lon: 80.4890,
  },
  {
    name: "Knuckles Mountain Range",
    category: "nature",
    duration: 2,
    cost: 4000,
    image: "https://i0.wp.com/amazinglanka.com/wp/wp-content/uploads/2014/09/knuckles-01.jpg?fit=800%2C450&ssl=1",
    description: "Hiking destination with lush forests and rivers.",
    lat: 7.4333,
    lon: 80.7667,
  },
  {
    name: "Sinharaja Forest Reserve",
    category: "nature",
    duration: 2,
    cost: 3800,
    image: "https://theportuguesetraveler.com/wp-content/uploads/2024/11/sinharaja-forest-reserve-rainforest-sri-lanka-137.jpg.webp",
    description: "UNESCO World Heritage rainforest with rich biodiversity.",
    lat: 6.3710,
    lon: 80.4500,
  },
  {
    name: "Victoria Reservoir",
    category: "nature",
    duration: 1,
    cost: 1500,
    image: "https://img.freepik.com/premium-photo/victoria-reservoir-kandy-sri-lanka_114775-433.jpg",
    description: "Scenic reservoir surrounded by mountains and forests.",
    lat: 7.5000,
    lon: 80.7667,
  },
  {
    name: "Ravana Falls",
    category: "nature",
    duration: 1,
    cost: 800,
    image: "https://digitaltravelcouple.com/wp-content/uploads/2019/12/ravana-falls-sri-lanka-pool.jpg?ezimgfmt=rs:767x479/rscb19/ng:webp/ngcb19",
    description: "Famous waterfall near Ella.",
    lat: 6.8700,
    lon: 81.0400,
  },
  {
    name: "Lipton's Seat",
    category: "nature",
    duration: 1,
    cost: 1200,
    image: "https://www.orienthotelsl.com/wp-content/uploads/2023/01/Hike-to-Liptons-seat-800x600-1.webp",
    description: "Viewpoint overlooking tea plantations.",
    lat: 6.8830,
    lon: 80.9550,
  },
  {
    name: "Seetha Eliya",
    category: "nature",
    duration: 1,
    cost: 800,
    image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/6c/e0/df/the-kovil-at-the-roadside.jpg?w=900&h=500&s=1",
    description: "Small scenic village with natural attractions.",
    lat: 6.9667,
    lon: 80.7667,
  },

  // ===== Adventure =====
  {
    name: "Kitulgala White Water Rafting",
    category: "adventure",
    duration: 1,
    cost: 5500,
    image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/1e/ce/a3.jpg",
    description: "Thrilling white-water rafting through tropical rainforests.",
    lat: 6.9667,
    lon: 80.6000,
  },
  {
    name: "Safari in Yala National Park",
    category: "adventure",
    duration: 2,
    cost: 8000,
    image: "https://www.22weligambay.com/images/experiences/yala-national-park/yala-slider1.jpg",
    description: "Sri Lanka’s most famous wildlife park—leopards, elephants & more.",
    lat: 6.3590,
    lon: 81.5300,
  },
  {
    name: "Ziplining in Kandy",
    category: "adventure",
    duration: 1,
    cost: 2000,
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/11/67/35/3f.jpg",
    description: "Adrenaline-pumping zipline with panoramic hill views.",
    lat: 7.2906,
    lon: 80.6337,
  },
  {
    name: "Knuckles Trekking",
    category: "adventure",
    duration: 2,
    cost: 4500,
    image: "https://thema-collection.imgix.net/sites/14/2025/05/High-Knuckles-Glamping-in-Sri-Lanka.jpg?w=940&h=760&&fit=crop&crop=center&auto=format,enhance&q=25",
    description: "Challenging treks with amazing views.",
    lat: 7.4333,
    lon: 80.7667,
  },
  {
    name: "Haputale Hiking",
    category: "adventure",
    duration: 1,
    cost: 2500,
    image: "https://www.srilankanexpeditions.com/images/destinations-in-sri-lanka/best-things-to-do-in-haputale/best-things-to-do-in-haputale-01.jpg",
    description: "Hiking trails with stunning hill country views.",
    lat: 6.7700,
    lon: 80.9930,
  },
  {
    name: "Udawalawe Safari",
    category: "adventure",
    duration: 1,
    cost: 3000,
    image: "https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/0b/2a/7c.jpg",
    description: "Safari park famous for elephants and wildlife.",
    lat: 6.4500,
    lon: 81.0900,
  },
  {
    name: "Ella Rock Climb",
    category: "adventure",
    duration: 1,
    cost: 2000,
    image: "https://www.srilankainstyle.com/storage/app/media/Experiences/Ella%20Rock%20Climb/Ella-Rock-Climb-slider-4.jpg",
    description: "Moderate rock climb with scenic views.",
    lat: 6.8440,
    lon: 81.0460,
  },
  {
    name: "Kitulgala Canopy Tour",
    category: "adventure",
    duration: 1,
    cost: 2800,
    image: "https://www.kitulgalaadventures.com/booking/package_img/1468494410jump4.jpg",
    description: "Zipline and canopy adventure in lush forest.",
    lat: 6.9667,
    lon: 80.6000,
  },
  {
    name: "Surfing in Arugam Bay",
    category: "adventure",
    duration: 2,
    cost: 4000,
    image: "https://www.srilankainstyle.com/storage/app/media/Experiences/Surfs%20up%20in%20Arugam%20Bay/Surfs-up-in-Arugam-Bay-slider-4.jpg",
    description: "World-class surfing destination.",
    lat: 6.8413,
    lon: 81.6980,
  },
  {
    name: "Mountain Biking in Nuwara Eliya",
    category: "adventure",
    duration: 1,
    cost: 1800,
    image: "https://lakpura.com/cdn/shop/products/LKI7217391-04-E.jpg?v=1679987301&width=1445",
    description: "Adventure biking trails through tea estates.",
    lat: 6.9700,
    lon: 80.7890,
  },
];

module.exports = destinations;
